
import java.util.ArrayList;

/**/

public class FenetreQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());
    private ArrayList<Question> lesQuestions;
    private int indexQuestionCourante = 0;
    private int score = 0;
    
    public FenetreQuiz() {
        initComponents();
        lesQuestions  = new ArrayList<>() ;
        initQuestions();
        afficherQuestionCourante();
        next_Question.setText("Question suivante");
    }
    private void initQuestions(){
        lesQuestions.add(new Question(
        "Quelle est la capitale de la France ?", "Paris", "Lyon", "Marseille", "Toulouse", 1));

        lesQuestions.add(new Question(
        "Combien font 8 × 3 ?", "20", "24", "18", "26",3));

        lesQuestions.add(new Question(
        "Quelle est la planète la plus proche du Soleil ?", "Venus", "Terre", "Mercure", "Mars",2));

        lesQuestions.add(new Question(
        "Qui a peint la Joconde ?", "Van Gogh", "Monet", "Da Vinci", "Picasso", 4));

        lesQuestions.add(new Question(
        "Quel est l’élément chimique O ?", "Or", "Oxygène", "Osmium", "Ozone",2 ));
    }
    
    private void  afficherQuestionCourante(){
        Question Q = lesQuestions.get(indexQuestionCourante);
        
        Question_n.setText(Q.getIntitule());
        
        Prop1.setText(Q.getProposition1());
        Prop2.setText(Q.getProposition2());
        Prop3.setText(Q.getProposition3());
        Prop4.setText(Q.getProposition4());
        
        Prop1.setEnabled(true);
        Prop2.setEnabled(true);
        Prop3.setEnabled(true);
        Prop4.setEnabled(true);
        
        Feedback.setText("");
    }
    
    private void verifierReponse(int choix){
        Question Q = lesQuestions.get(indexQuestionCourante);
        
        if (choix == Q.getIndexBonneReponse()){
            Feedback.setText("Bonne reponse !");
            score++;
            Score.setText("Score : " + score);
        }
        else {
            Feedback.setText("Mauvaise response.");
        }
        Prop1.setEnabled(false);
        Prop2.setEnabled(false);
        Prop3.setEnabled(false);
        Prop4.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Question_n = new javax.swing.JLabel();
        Prop1 = new javax.swing.JButton();
        Prop2 = new javax.swing.JButton();
        Prop3 = new javax.swing.JButton();
        Prop4 = new javax.swing.JButton();
        Feedback = new javax.swing.JLabel();
        next_Question = new javax.swing.JButton();
        Score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Question_n.setText("jLabel1");
        getContentPane().add(Question_n, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 300, -1));

        Prop1.setText("jButton1");
        Prop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prop1ActionPerformed(evt);
            }
        });
        getContentPane().add(Prop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 110, -1, -1));

        Prop2.setText("jButton2");
        Prop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prop2ActionPerformed(evt);
            }
        });
        getContentPane().add(Prop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 110, -1, -1));

        Prop3.setText("jButton3");
        Prop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prop3ActionPerformed(evt);
            }
        });
        getContentPane().add(Prop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 110, -1, -1));

        Prop4.setText("jButton4");
        Prop4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prop4ActionPerformed(evt);
            }
        });
        getContentPane().add(Prop4, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 110, -1, -1));

        Feedback.setText("jLabel1");
        getContentPane().add(Feedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 210, -1));

        next_Question.setText("jButton1");
        next_Question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_QuestionActionPerformed(evt);
            }
        });
        getContentPane().add(next_Question, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 253, 130, -1));

        Score.setText("jLabel2");
        getContentPane().add(Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 20, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Prop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prop1ActionPerformed
     verifierReponse(1);
    }//GEN-LAST:event_Prop1ActionPerformed

    private void Prop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prop2ActionPerformed
     verifierReponse(2);
    }//GEN-LAST:event_Prop2ActionPerformed

    private void Prop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prop3ActionPerformed
     verifierReponse(3);
    }//GEN-LAST:event_Prop3ActionPerformed

    private void Prop4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prop4ActionPerformed
     verifierReponse(4);
    }//GEN-LAST:event_Prop4ActionPerformed

    private void next_QuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_QuestionActionPerformed
        indexQuestionCourante++;
    if (indexQuestionCourante < lesQuestions.size()){
        afficherQuestionCourante();
    }
    else{
        Feedback.setText("Quiz termine !\n Score : " +score+ "/"+ lesQuestions.size());
    
    next_Question.setEnabled(false);
    
    Prop1.setEnabled(false);
    Prop2.setEnabled(false);
    Prop3.setEnabled(false);
    Prop4.setEnabled(false);
        }
    }//GEN-LAST:event_next_QuestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Feedback;
    private javax.swing.JButton Prop1;
    private javax.swing.JButton Prop2;
    private javax.swing.JButton Prop3;
    private javax.swing.JButton Prop4;
    private javax.swing.JLabel Question_n;
    private javax.swing.JLabel Score;
    private javax.swing.JButton next_Question;
    // End of variables declaration//GEN-END:variables
}
