
import java.awt.Color;

/**/

/**/
public class Cadena extends javax.swing.JFrame {
   private final CadenaLogic jeu;
   private boolean jeuTermine = false;
   
   private int chiffre1 = 0;
   private int chiffre2 = 0;
   private int chiffre3 = 0;
   private int chiffre4 = 0;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadena.class.getName());

    /**
     * Creates new form Cadena
     */
    public Cadena() {
        initComponents();
        
          texte_lbl_nb_chiffres_exacts.setText("0");
          texte_lbl_nb_chiffres_haut.setText("0");
          texte_lbl_nb_chiffres_bas.setText("0");
          
          texte_score.setText("0 sur 5");
          
           texte_message.setText("");

        jeu = new CadenaLogic();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        texte_message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        texte_intro.setText("Trouvez le bon code en au moins 5 tentatives !");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 24, -1, 46));

        up_chiffre_1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        up_chiffre_1.setText("+");
        up_chiffre_1.setAutoscrolls(true);
        up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 105, 27, -1));

        up_chiffre_2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        up_chiffre_2.setText("+");
        up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_2ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 105, 27, -1));

        up_chiffre_3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        up_chiffre_3.setText("+");
        up_chiffre_3.setToolTipText("");
        up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_3ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 105, 26, -1));

        up_chiffre_4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        up_chiffre_4.setText("+");
        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_4ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 105, 27, -1));

        texte_chiffre_0.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        texte_chiffre_0.setText("0");
        getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 142, -1, -1));

        texte_chiffre_1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        texte_chiffre_1.setText("0");
        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 142, -1, -1));

        texte_chiffre_2.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        texte_chiffre_2.setText("0");
        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 142, -1, -1));

        texte_chiffre_3.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        texte_chiffre_3.setText("0");
        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 142, -1, -1));

        down_chiffre_1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        down_chiffre_1.setText("-");
        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 210, 27, -1));

        down_chiffre_2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        down_chiffre_2.setText("-");
        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_2ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 210, 27, -1));

        down_chiffre_3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        down_chiffre_3.setText("-");
        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_3ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 210, 26, -1));

        down_chiffre_4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        down_chiffre_4.setText("-");
        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_4ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 210, 26, -1));

        bouton_tester.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        bouton_tester.setText("Tester");
        bouton_tester.setActionCommand("Tester");
        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_testerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 161, -1, -1));

        texte_lbl_nb_chiffres_exacts.setText("jLabel6");
        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 282, -1, -1));

        texte_lbl_nb_chiffres_haut.setText("jLabel7");
        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 313, -1, -1));

        texte_lbl_nb_chiffres_bas.setText("jLabel8");
        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 344, -1, -1));

        texte_nb_chiffres_exacts.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        texte_nb_chiffres_exacts.setText("Nombre de chiffres exacts :");
        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 280, 205, -1));

        texte_nb_chiffres_haut.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        texte_nb_chiffres_haut.setText("Nombre de chiffres trop haut :");
        texte_nb_chiffres_haut.setToolTipText("Nombre");
        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 311, 205, -1));

        texte_nb_chiffres_bas.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        texte_nb_chiffres_bas.setText("Nombre de chiffres trop bas :");
        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 342, 205, -1));

        texte_score.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        texte_score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_score.setText("0 sur 5");
        texte_score.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        texte_score.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 135, 116));

        texte_tentatives.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        texte_tentatives.setText("Tentatives:");
        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        bouton_recommencer.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bouton_recommencer.setText("Recommencer");
        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_recommencerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        texte_message.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        texte_message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_message.setText("jLabel1");
        texte_message.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(texte_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 81, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        chiffre1++;

    if (chiffre1 > 9) {
        chiffre1 = 0;
    }

    texte_chiffre_0.setText("" + chiffre1);

    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
       chiffre2++;

    if (chiffre2 > 9) {
        chiffre2 = 0;
    }

    texte_chiffre_1.setText("" + chiffre2);

    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        chiffre3++;

    if (chiffre3 > 9) {
        chiffre3 = 0;
    }

    texte_chiffre_2.setText("" + chiffre3);

    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
       chiffre4++;

    if (chiffre4 > 9) {
        chiffre4 = 0;
    }

    texte_chiffre_3.setText("" + chiffre4);

        
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        chiffre1--;

    if (chiffre1 < 0) {
        chiffre1 = 9;
    }

    texte_chiffre_0.setText("" + chiffre1);

    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
       chiffre2--;

    if (chiffre2 < 0) {
        chiffre2 = 9;
    }

    texte_chiffre_1.setText("" + chiffre2);

    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        chiffre3--;

    if (chiffre3 < 0) {
        chiffre3 = 9;
    }

    texte_chiffre_2.setText("" + chiffre3);

    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
      chiffre4--;

    if (chiffre4 < 0) {
        chiffre4 = 9;
    }

    texte_chiffre_3.setText("" + chiffre4);

    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed

            
          if (jeuTermine){
              return;
          }              
            int[] essai = new int[4];
            essai[0] = Integer.parseInt(texte_chiffre_0.getText());
            essai[1] = Integer.parseInt(texte_chiffre_1.getText());
            essai[2] = Integer.parseInt(texte_chiffre_2.getText());
            essai[3] = Integer.parseInt(texte_chiffre_3.getText());


            Resultat res = jeu.test(essai);
            
            texte_lbl_nb_chiffres_exacts.setText("" + res.exact);
            texte_lbl_nb_chiffres_haut.setText("" + res.haut);
            texte_lbl_nb_chiffres_bas.setText("" + res.bas);
            
           texte_score.setText(jeu.getTentative() + " sur "+ jeu.getMax_tentative());
           
           if (res.exact == 4){
               texte_message.setText("Gagne !");
               texte_message.setForeground(Color.GREEN);
               jeuTermine = true;
           }
           else if (jeu.getTentative() >= jeu.getMax_tentative()){
               texte_message.setText("Perdu !");
               texte_message.setForeground(Color.red);
               jeuTermine = true;
           }
           else {
               texte_message.setText("");
           }
    }//GEN-LAST:event_bouton_testerActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed

        
        jeu.reset();
        
        chiffre1=chiffre2=chiffre3=chiffre4=0;
      
        texte_chiffre_0.setText("0");
        texte_chiffre_1.setText("0");
        texte_chiffre_2.setText("0");
        texte_chiffre_3.setText("0");
        
        texte_lbl_nb_chiffres_exacts.setText("0");
        texte_lbl_nb_chiffres_haut.setText("0");
        texte_lbl_nb_chiffres_bas.setText("0");
        
        texte_score.setText("0 sur 5");
        texte_message.setText("");
        
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cadena().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_message;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
